# Generated by Django 2.2.24 on 2021-09-08 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='school_grade',
            field=models.CharField(choices=[('1', '1年生'), ('2', '2年生'), ('3', '3年生'), ('4', '4年生'), ('5', '大学院生')], max_length=1),
        ),
    ]
