# Generated by Django 2.2.24 on 2021-08-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_auto_20210824_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='picture',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
