# Generated by Django 2.2.24 on 2021-08-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_auto_20210824_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='picture',
            field=models.ImageField(default='images/initial.jpeg', upload_to='images/'),
        ),
    ]
