# Generated by Django 2.2.24 on 2021-08-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_auto_20210824_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
