# Generated by Django 2.2.24 on 2021-12-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0023_auto_20211127_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='hobby1',
            field=models.CharField(choices=[('スポーツ', 'スポーツ'), ('読書', '読書'), ('旅行', '旅行'), ('カメラ', 'カメラ'), ('ドラマ', 'ドラマ'), ('映画', '映画'), ('ジャニーズ', 'ジャニーズ'), ('アニメ', 'アニメ'), ('漫画', '漫画'), ('料理', '料理'), ('お笑い', 'お笑い'), ('K-POP', 'K-POP'), ('ドライブ', 'ドライブ'), ('ゲーム', 'ゲーム')], max_length=20),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='hobby2',
            field=models.CharField(choices=[('スポーツ', 'スポーツ'), ('読書', '読書'), ('旅行', '旅行'), ('カメラ', 'カメラ'), ('ドラマ', 'ドラマ'), ('映画', '映画'), ('ジャニーズ', 'ジャニーズ'), ('アニメ', 'アニメ'), ('漫画', '漫画'), ('料理', '料理'), ('お笑い', 'お笑い'), ('K-POP', 'K-POP'), ('ドライブ', 'ドライブ'), ('ゲーム', 'ゲーム')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hobby',
            name='hobby3',
            field=models.CharField(choices=[('スポーツ', 'スポーツ'), ('読書', '読書'), ('旅行', '旅行'), ('カメラ', 'カメラ'), ('ドラマ', 'ドラマ'), ('映画', '映画'), ('ジャニーズ', 'ジャニーズ'), ('アニメ', 'アニメ'), ('漫画', '漫画'), ('料理', '料理'), ('お笑い', 'お笑い'), ('K-POP', 'K-POP'), ('ドライブ', 'ドライブ'), ('ゲーム', 'ゲーム')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='q1',
            field=models.IntegerField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')]),
        ),
    ]
